In [58]:
import numpy as np

In [59]:
a1=[1,2,3,5,7,4,9,6]

In [60]:
a=np.array(a1)

In [61]:
a

array([1, 2, 3, 5, 7, 4, 9, 6])

In [62]:
a.ndim

1

a[2]

In [63]:
a=np.array([[1,5],[4,6],[7,2],[10,8]])
a

array([[ 1,  5],
       [ 4,  6],
       [ 7,  2],
       [10,  8]])

In [64]:
a.size

8

In [65]:
a.dtype

dtype('int32')

In [66]:
a.ndim

2

In [70]:
a=np.array([[1,5],[4,6],[7,2]],dtype='float')
a

array([[1., 5.],
       [4., 6.],
       [7., 2.]])

In [71]:
a.dtype

dtype('float64')

In [72]:
a.size

6

In [73]:
a.shape

(3, 2)

In [75]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
l=range(5)
l

range(0, 5)

In [82]:
l[2],l[0],l[4]

(2, 0, 4)

In [86]:
b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
b[2]

3

In [88]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [89]:
a

array([[1., 5.],
       [4., 6.],
       [7., 2.]])

In [95]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
b.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [98]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
b.min()

1

In [101]:
b.max()

9

In [102]:
b.sum()

45

In [103]:
a

array([[1., 5.],
       [4., 6.],
       [7., 2.]])

In [104]:
a.sum()

25.0

In [105]:
a.sum(axis=1)

array([ 6., 10.,  9.])

In [106]:
a.sum(axis=0)

array([12., 13.])

In [107]:
np.sqrt(a)

array([[1.        , 2.23606798],
       [2.        , 2.44948974],
       [2.64575131, 1.41421356]])

In [108]:
np.std(a)

2.1147629234082537

In [109]:
c=np.array([[3,4],[7,9]])

In [110]:
d=np.array([[10,1],[6,3]])

In [112]:
c,d

(array([[3, 4],
        [7, 9]]),
 array([[10,  1],
        [ 6,  3]]))

In [113]:
c+d

array([[13,  5],
       [13, 12]])

In [114]:
c-d

array([[-7,  3],
       [ 1,  6]])

In [115]:
c.dot(d)

array([[ 54,  15],
       [124,  34]])