**<h1>Exploring NumPy 02</h1>**

In [24]:
import numpy as np

In [25]:
array1=[1,2,3,4]

In [39]:
array1=np.array(array1)   #Converts list into array

In [40]:
array1

array([1, 2, 3, 4])

In [41]:
array1+5

array([6, 7, 8, 9])

In [42]:
array1/5

array([0.2, 0.4, 0.6, 0.8])

In [43]:
array2=[1,0,3,0]

In [44]:
array2=np.array(array2)

In [45]:
array2

array([1, 0, 3, 0])

In [46]:
array1+array2

array([2, 2, 6, 4])

In [57]:
np.cos(array1) #Finds the Trignometric value of the mentioned array

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [58]:
array1**2

array([ 1,  4,  9, 16])

In [59]:
a=[1,2,3]
b=[7,8,9]

In [60]:
a=np.array(a)
b=np.array(b)

In [61]:
a*b

array([ 7, 16, 27])

In [65]:
a1=np.array([[1,2,3],[4,5,6]])  #Creating a 2d Array

In [66]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a1.shape # shape returns the dimensions of the array

(2, 3)

In [70]:
a1.ndim  # ndim returns the number of dimensions of the array

2

In [72]:
a1.dtype # dtype returns the data type of the array elements

dtype('int32')

In [74]:
a1.size # size returns the total number of elements in the array

6

**Accessing/Changing specific elements, rows, columns, etc.**

In [89]:
a=([1,2,3,4,5,6,7],
   [8,9,10,11,12,13,14],
  [15,16,17,18,19,20,21],
  [22,23,24,25,26,27,28])

In [90]:
a=np.array(a)

In [91]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

**Below is the Syntax for slicing**

**a[row_start:row_end, col_start:col_end]** 

In [93]:
# a[row, col] will access the element at the specified row and column
# For example, a[1, 5] accesses the 2nd row and 6th column, which is 13
a[1,5]

13

In [94]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [95]:
a[0:,]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [97]:
a[0:3,1:5]   #This will give rows 0 to 2 and columns 1 to 4

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12],
       [16, 17, 18, 19]])

In [99]:
a[:,:] #Will give everything!

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [101]:
# Getting a specific column
a[:,1:3]

array([[ 2,  3],
       [ 9, 10],
       [16, 17],
       [23, 24]])

**Using Stepsize**<br>
**Syntax: a[row_start:row_end:row_step, col_start:col_end:col_step]**

In [104]:
a[0, 1:-1:2]

array([2, 4, 6])

In [105]:
a[0,1::2]

array([2, 4, 6])

**Replacing values using slicing**

In [111]:
a[1,5]=100
a

array([[  1,   2,   1,   4,   5,   6, 101],
       [  8,   9,   2,  11,  12, 100, 102],
       [ 15,  16,   3,  18,  19,  20, 103],
       [ 22,  23,   4,  25,  26,  27, 104]])

In [112]:
a[:,-1]=[101,102,103,104]
a

array([[  1,   2,   1,   4,   5,   6, 101],
       [  8,   9,   2,  11,  12, 100, 102],
       [ 15,  16,   3,  18,  19,  20, 103],
       [ 22,  23,   4,  25,  26,  27, 104]])

**Using a 3D Array**

In [119]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [120]:
b[0:2,1,0]

array([3, 7])

**Introduction to Different Types of Arrays in NumPy**

In [121]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [122]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.full((2,2),99)  # Will make an array with shape(2,2) and fills all with 99

array([[99, 99],
       [99, 99]])

In [127]:
np.full_like(a,3)  # Creating a new array with the same shape as 'a' and fill it with 4

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [129]:
# Creating Random decimal numbers
np.random.rand(3,3)

array([[0.80293   , 0.32119183, 0.47639153],
       [0.97538266, 0.19284875, 0.11802698],
       [0.54458702, 0.80243906, 0.27737621]])

In [134]:
np.random.randint(0, 10)  #Without using size it'll give random integer in the range that is being mentioned

3

In [135]:
# Using randint with size 
np.random.randint(10,20,size=(2,3))

array([[17, 14, 13],
       [15, 13, 15]])

In [137]:
# Identity matrix: square matrix with 1s on the diagonal and 0s elsewhere. Creates a 3x3 matrix. Identity uses 2d arrays only

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
# Repeating an array
# # Repeat the elements of 'arr' 3 times along the first axis (rows)

In [144]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [146]:
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [147]:
r1 = np.repeat(arr,3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [149]:
a1=np.ones((5,5))
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
a2=np.zeros((3,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
a2[1,1]=9

In [152]:
a2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [153]:
a1[1:-1,1:-1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [156]:
a1[1:-1,1:-1]=a2
a1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Copying arrays**

In [159]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
a

[100   2   3]


array([1, 2, 3])

**Mathematics**

In [160]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [161]:
a+2

array([3, 4, 5, 6])

In [162]:
a-2

array([-1,  0,  1,  2])

In [163]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [164]:
a*2

array([2, 4, 6, 8])

In [166]:
b=np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [167]:
a+b

array([2, 2, 4, 4])

In [168]:
a**2

array([ 1,  4,  9, 16])

In [170]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [172]:
a = np.ones((2,3))
print(a)
print()

b = np.full((3,2), 2)
print(b)
print()

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]



array([[6., 6.],
       [6., 6.]])

In [174]:
# Finding the determinant
# Output will be 1.0, because the determinant of an identity matrix is always 1

c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**

In [175]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
print(np.min(s))
print(np.max(s))

1
6


In [178]:
print(np.max(s, axis=1))
print()
print(np.sum(s, axis=0))

[3 6]

[5 7 9]


**Reorganizing Arrays**

In [184]:
# Below it will raise an error because reshaping a 2x4 array to 2x3 is not possible

In [185]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [186]:
# The total number of elements in the original array must match the total number of elements in the reshaped array

In [187]:
after=before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [188]:
# Vertically stacking vectors


v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [190]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])