**<h1>Exploring NumPy</h1>**

In [2]:
import numpy as np

In [3]:
array1=[1,3,5,7,9]

In [4]:
type(array1)

list

In [5]:
array1=np.array(array1)

In [6]:
array1

array([1, 3, 5, 7, 9])

In [7]:
type(array1)

numpy.ndarray

**Performing Mathematical Operations**

In [8]:
array2=array1*2

In [9]:
array2

array([ 2,  6, 10, 14, 18])

In [10]:
array2+3

array([ 5,  9, 13, 17, 21])

In [11]:
array2

array([ 2,  6, 10, 14, 18])

**Creating a 2 Array and exploring more about it**

In [12]:
array3=[[1,2,3],[4,5,6]]

In [13]:
array3

[[1, 2, 3], [4, 5, 6]]

In [14]:
array3=np.array(array3)
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.mean(array3)  #Finding Sum of Array using Mean function of NumPy

3.5

In [16]:
np.sum(array3)  #Finding Sum of Array using Sum function of NumPy

21

In [17]:
np.ndim(array3)   #Checking Dimenion of Array

2

In [18]:
array3.nbytes  #Returns total bytes consumed by elements

24

In [19]:
array3.size  # Returns total number of elements in the Array

6

In [20]:
array3[1,2]

6

In [21]:
array3[0]

array([1, 2, 3])

In [22]:
array3.shape  #Returns Rows and Columns present in Array

(2, 3)

In [23]:
array4=[[1,3,6,5,4,2],[8,7,10,9,11,12]]
array4=np.array(array4)

In [24]:
array4

array([[ 1,  3,  6,  5,  4,  2],
       [ 8,  7, 10,  9, 11, 12]])

In [25]:
array4[1,3]=0

array4

array([[ 1,  3,  6,  5,  4,  2],
       [ 8,  7, 10,  0, 11, 12]])

In [26]:
array4[:,2]=99,100

In [27]:
array4

array([[  1,   3,  99,   5,   4,   2],
       [  8,   7, 100,   0,  11,  12]])

In [28]:
array5=np.zeros((2,3))

In [29]:
array5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
array5=np.ones((2,3))
array5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
array3d = np.zeros((3, 2, 3))   #Creating a 3d ararray3d
array3d

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [33]:
np.random.rand(3,2)  #if you just use rand you can only give size and you cant give range

array([[0.96126885, 0.27614704],
       [0.55937682, 0.77301922],
       [0.0594236 , 0.85289106]])

In [34]:
# If you use randint you can also provide the range along with size

In [35]:
np.random.randint(1, 10, (2, 2))   # array with random integers between 1  to 9, Size is 2x2


array([[5, 8],
       [9, 8]])

In [36]:
np.random.rand(2,3)

array([[0.35137805, 0.46749164, 0.60321837],
       [0.11005383, 0.87484437, 0.26698096]])

In [37]:
# np.repeat will repeat the desired array the speicified number of times

In [38]:
# 'arr': The original array that you want to repeat.
# '3': The number of times you want to repeat the elements of the array.
# 'axis=0': Specifies the axis along which to repeat the elements.
#           In this case, axis=0 refers to repeating along the rows.

In [41]:
arr=[[1,2,3]]
r1=np.repeat(arr,3,axis=0)  
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
arr=[[1,2,3]]
r1=np.repeat(arr,3,axis=1)  
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])